require('mattjamesdev.plugins.lsp')
require('mattjamesdev.plugins.luasnip')
-- require('mattjamesdev.plugins.efm-langserver')
require('mattjamesdev.plugins.null-ls')
require('mattjamesdev.plugins.treesitter')
require('mattjamesdev.plugins.telescope')
require('mattjamesdev.plugins.lualine')
require('mattjamesdev.plugins.nvim-tree')
require('mattjamesdev.plugins.nvim-autopairs')
require('mattjamesdev.plugins.toggleterm')
require('mattjamesdev.plugins.bufferline')
require('mattjamesdev.plugins.alpha-nvim')
require('mattjamesdev.plugins.which-key')
require('mattjamesdev.plugins.neodim')
require('mattjamesdev.plugins.nvim-notify')
require('mattjamesdev.plugins.colourscheme')
